# Generated by Django 4.2.23 on 2025-08-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('short_description', models.TextField(max_length=500, verbose_name='Краткое описание')),
                ('long_description', models.TextField(verbose_name='Длинное описание')),
                ('date_time', models.DateTimeField(verbose_name='Дата и время проведения')),
                ('duration', models.DurationField(verbose_name='Продолжительность')),
                ('location', models.CharField(max_length=300, verbose_name='Место проведения')),
                ('age_limit', models.PositiveIntegerField(default=0, verbose_name='Возрастное ограничение')),
                ('max_participants', models.PositiveIntegerField(verbose_name='Максимальное количество участников')),
                ('min_participants', models.PositiveIntegerField(default=1, verbose_name='Минимальное количество участников')),
                ('current_participants', models.PositiveIntegerField(default=0, verbose_name='Текущее количество участников')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('prime_points', models.PositiveIntegerField(default=0, verbose_name='Баллы прайма')),
                ('main_image', models.ImageField(upload_to='events/main/', verbose_name='Главное фото')),
                ('extra_media', models.FileField(blank=True, null=True, upload_to='events/extra/', verbose_name='Доп. фото/видео')),
                ('participants_list', models.TextField(blank=True, verbose_name='Список участников')),
            ],
        ),
    ]
