# Generated by Django 4.2.23 on 2025-08-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
        migrations.AddField(
            model_name='event',
            name='eng_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название (англ.)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='age_limit',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Возрастное ограничение'),
        ),
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Продолжительность'),
        ),
        migrations.AlterField(
            model_name='event',
            name='extra_media',
            field=models.FileField(blank=True, null=True, upload_to='dop_event_photo/', verbose_name='Доп. фото/видео'),
        ),
        migrations.AlterField(
            model_name='event',
            name='long_description',
            field=models.TextField(blank=True, verbose_name='Длинное описание'),
        ),
        migrations.AlterField(
            model_name='event',
            name='main_image',
            field=models.ImageField(upload_to='main_event_photo/', verbose_name='Главное фото'),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимальное количество участников'),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена'),
        ),
    ]
