# Generated by Django 4.2.23 on 2025-08-13 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_event_options_event_eng_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='extra_media',
        ),
        migrations.AlterField(
            model_name='event',
            name='eng_name',
            field=models.CharField(max_length=200, verbose_name='Название (англ.)'),
        ),
        migrations.CreateModel(
            name='EventMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_file', models.FileField(upload_to='event_media/', verbose_name='Фото/видео')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='main.event')),
            ],
        ),
    ]
