# Generated by Django 4.2.23 on 2025-08-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_event_extra_media_alter_event_eng_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='current_participants',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Текущее количество участников'),
        ),
        migrations.AlterField(
            model_name='event',
            name='min_participants',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Минимальное количество участников'),
        ),
        migrations.AlterField(
            model_name='event',
            name='prime_points',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Баллы прайма'),
        ),
    ]
