# Generated by Django 4.2.23 on 2025-08-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_event_current_participants_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='eng_name',
        ),
        migrations.AddField(
            model_name='event',
            name='na_angl',
            field=models.CharField(default=1, max_length=200, verbose_name='Без пробелов на английском'),
            preserve_default=False,
        ),
    ]
