# Generated by Django 4.2.23 on 2025-08-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_participant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='na_angl',
        ),
        migrations.AddField(
            model_name='event',
            name='eng_name',
            field=models.CharField(default='temp', max_length=200, verbose_name='Название (англ.)'),
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Slug'),
        ),
    ]
