# Generated by Django 4.2.23 on 2025-09-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_event_na_angl_event_eng_name_event_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='current_participants',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Текущее количество участников'),
        ),
    ]
